# -*- coding: utf-8 -*-
"""
Legacy słowniki DE-Ost GU (Filialbau) — markery filtrów / kompatybilność importów.

Kampania Hurt Matbud / Polska NIE szuka niemieckich Generalunternehmer.
Discovery Serper buduje się z pl_wojewodztwa.py (polscy podwykonawcy budowlani w DE).
Poniższe SERPER_DISCOVERY_* są historyczne; runtime nadpisuje je w de_gu_keywords.py.
"""

# Historyczne — runtime PL używa de_gu_keywords.build_discovery_terms().
SERPER_DISCOVERY_REGION_SUFFIX = "Polska Niemcy podwykonawca budowlany"

SERPER_DISCOVERY_TERMS = [
    "podwykonawca budowlany Polska Niemcy",
    "firma budowlana realizacje Niemcy sp. z o.o.",
    "wyposażenie sklepów Polska Deutschland",
    "wykończenia restauracje hotele Niemcy",
    "posadzki przemysłowe hale Niemcy",
    "montaż drogerii Rossmann DM Niemcy",
    "instalacje HVAC sklepy Niemcy Polska",
    "Ladenbau Firma Polska",
    "Innenausbau Polen Deutschland",
    "hale przemysłowe podwykonawca Niemcy",
]

SERPER_DISCOVERY_FALLBACK_TERMS = list(SERPER_DISCOVERY_TERMS)

# --- legacy markery GU/retail (importowane przez de_gu_keywords) ---

GU_ROLE_KEYWORDS = (
    "generalunternehmer",
    "generalunternehmen",
    "generalunternehmerleistung",
    "komplettgeneralunternehmer",
    "komplettgeneralunternehmerleistung",
    "hauptauftragnehmer",
    "totalunternehmer",
    "bauunternehmen",
    "bauunternehmung",
    "bauausführender",
    "bauausfuehrender",
    "bauausführung",
    "bauausfuehrung",
    "generalübernehmer",
    "generaluebernehmer",
    "gu-leistung",
    "gu ",
)

# Obowiązkowe sieci w referencjach / na stronie (bez wzmianki → odrzucenie)
REQUIRED_RETAIL_CHAIN_KEYWORDS = (
    "aldi",
    "rewe",
    "edeka",
    "netto",
    "penny",
    "kaufland",
    "lidl",
    "norma",
)

RETAIL_CHAIN_KEYWORDS = (
    "aldi",
    "aldi nord",
    "aldi süd",
    "aldi sued",
    "penny",
    "kaufland",
    "netto",
    "netto marken-discount",
    "rewe",
    "rewe group",
    "lidl",
    "edeka",
    "norma",
    "nahkauf",
    "toom",
    "tegut",
    "marktkauf",
    "hit ",
    "famila",
    "combi",
    "globus",
    "selgros",
    "metro",
    "rossmann",
    "action",
    "takko",
    "kik",
    "woolworth",
)

RETAIL_BUILD_KEYWORDS = (
    *GU_ROLE_KEYWORDS,
    "hochbau",
    "hoch- und rohbau",
    "hoch und rohbau",
    "rohbau",
    "rohbauarbeiten",
    "geschäftsbau",
    "geschaftsbau",
    "gewerbebau",
    "hallenbau",
    "industriebau",
    "stahlbau",
    "stahlbauhallen",
    "massivbau",
    "betonbau",
    "schlüsselfertigbau",
    "schluesselfertigbau",
    "schlüsselfertig",
    "schluesselfertig",
    "komplettbau",
    "komplettsanierung",
    "totalausführung",
    "totalausfuehrung",
    "totalauftrag",
    "aus einer hand",
    "alle gewerke aus einer hand",
    "schlüsselfertige übergabe",
    "schluesselfertige uebergabe",
    "rohbau bis fertigstellung",
    "komplette baumaßnahme",
    "komplette baumassnahme",
    "neubau",
    "umbau",
    "erweiterung",
    "erweiterungsbau",
    "anbau",
    "sanierung",
    "revitalisierung",
    "modernisierung",
    "generalsanierung",
    "abriss und neubau",
    "neubau filiale",
    "filialneubau",
    "filialumbau",
    "filialsanierung",
    "markterweiterung",
    "ladenerweiterung",
    "handelsbau",
    "handelsimmobilien",
    "filialgebäude",
    "filialgebaude",
    "filialstandort",
    "filialobjekt",
    "einzelhandelsimmobilie",
    "handelsimmobilie",
    "supermarkt-neubau",
    "supermarktneubau",
    "supermarktbau",
    "discounter-neubau",
    "discounterbau",
    "marktneubau",
    "ladenbau",
    "filialbau",
    "einzelhandelsbau",
    "einzelhandel",
    "einzelhandelsneubau",
    "discounter",
    "supermarkt",
    "marktbau",
    "handelsimmobil",
    "lebensmitteleinzelhandel",
    "food retail",
    "markterneuerung",
    "nahversorger",
    "verbrauchermarkt",
    "vollsortimenter",
    "sb-warenhaus",
    "handelsmarkt",
    "handelsprojekt",
    "einzelhandelsprojekt",
    "filialprojekt",
    "bauprojekt einzelhandel",
    "gewerbeimmobilie einzelhandel",
)

# Einzelhandel / Filialbau / Hochbau sklepów — bez wymogu Aldi/Rewe ani sekcji Referenzen
RETAIL_TRADE_ACTIVITY_KEYWORDS = (
    "filialbau",
    "ladenbau",
    "marktbau",
    "supermarktbau",
    "supermarkt-neubau",
    "supermarktneubau",
    "einzelhandelsbau",
    "handelsbau",
    "discounter",
    "discounterbau",
    "supermarkt",
    "einzelhandel",
    "lebensmitteleinzelhandel",
    "filialneubau",
    "filialumbau",
    "filialsanierung",
    "filialgebäude",
    "filialgebaude",
    "filialstandort",
    "einzelhandelsimmobilie",
    "handelsimmobilie",
    "handelsimmobilien",
    "handelsmarkt",
    "handelsprojekt",
    "einzelhandelsprojekt",
    "filialprojekt",
    "nahversorger",
    "verbrauchermarkt",
    "sb-warenhaus",
    "marktneubau",
    "markterweiterung",
    "ladenerweiterung",
    "filial",
)

RETAIL_HOCHBAU_CORE_KEYWORDS = (
    "hochbau",
    "hoch- und rohbau",
    "hoch und rohbau",
    "rohbau",
    "rohbauarbeiten",
    "geschäftsbau",
    "geschaftsbau",
    "gewerbebau",
    "hallenbau",
    "stahlbauhallen",
    "schlüsselfertigbau",
    "schluesselfertigbau",
    "komplettbau",
)

RETAIL_REFERENCE_KEYWORDS = (
    "referenz",
    "referenzen",
    "referenzprojekt",
    "referenzprojekte",
    "referenzliste",
    "projekte",
    "projekt",
    "projektübersicht",
    "projektuebersicht",
    "projektbeispiele",
    "bauprojekte",
    "objektübersicht",
    "objektuebersicht",
    "realisierung",
    "realisiert",
    "realisieren",
    "umgesetzt",
    "errichtet",
    "erstellt",
    "gebaut",
    "bauherr",
    "auftraggeber",
    "ausführung",
    "ausfuehrung",
    "bauleistung",
    "leistungsspektrum",
    "portfolio",
    "case study",
    "baustellen",
    "baustellenberichte",
    "unsere projekte",
)

RETAIL_URL_PRIORITY_KEYWORDS = (
    "referenz",
    "referenzen",
    "projekt",
    "projekte",
    "leistung",
    "leistungen",
    "bauleistungen",
    "ladenbau",
    "filial",
    "hochbau",
    "rohbau",
    "gewerbebau",
    "handelsbau",
    "einzelhandel",
    "discounter",
    "supermarkt",
    "marktbau",
    "markt",
    "portfolio",
    "realis",
    "bauprojekt",
    "aktuelle-projekte",
    "objekte",
    "karriere",
    "stellen",
    "jobs",
    "career",
    "auftraggeber",
)

# Typowe ścieżki Impressum (DE) — mail często tylko tam
IMPRESSUM_GUESS_PATHS = (
    "/impressum",
    "/impressum/",
    "/Impressum",
    "/de/impressum",
    "/de/impressum/",
    "/kontakt-impressum",
    "/kontakt/impressum",
    "/legal/impressum",
    "/unternehmen/impressum",
    "/site/impressum",
    "/imprint",
    "/imprint/",
)

RETAIL_CONTACT_LINK_KEYWORDS = (
    "kontakt",
    "contact",
    "impressum",
    "imprint",
    "o-nas",
    "ueber-uns",
    "über-uns",
    "referenz",
    "referenzen",
    "projekt",
    "projekte",
    "ladenbau",
    "filial",
    "hochbau",
    "rohbau",
    "gewerbebau",
    "handelsbau",
    "marktbau",
    "supermarkt",
    "anfrage",
    "leistungen",
    "bauleistungen",
    "karriere",
    "stellen",
    "stellenangebot",
    "jobs",
    "career",
)

DE_OST_REGION_KEYWORDS = (
    "neue bundesländer",
    "neue bundeslaender",
    "lausitz",
    "erzgebirge",
    "erzgebirgskreis",
    "mansfeld-südharz",
    "mansfeld-suedharz",
    "burgenlandkreis",
    "wartburgkreis",
    "unstrut-hainich",
    "ostprignitz-ruppin",
    "dahme-spreewald",
    "oder-spree",
    "havelland",
    "fläming",
    "flaeming",
    "sachsen-anhalt",
)

DE_OST_RURAL_HINTS = (
    "landkreis",
    "kreisstadt",
    "gemeinde",
    "kleinstadt",
    "ortschaft",
    " ort ",
    "dorf ",
    "dorfstraße",
    "dorfstrasse",
    "amtsbezirk",
    "verbandsgemeinde",
)

DE_OST_PLACE_MARKERS = (
    "leipzig",
    "dresden",
    "chemnitz",
    "erfurt",
    "potsdam",
    "cottbus",
    "halle",
    "jena",
    "zwickau",
    "goerlitz",
    "görlitz",
    "magdeburg",
    "ostdeutschland",
    "brandenburg",
    "sachsen",
    "thüringen",
    "thueringen",
    "wittenberge",
    "perleberg",
    "pritzwalk",
    "neuruppin",
    "rheinsberg",
    "angermünde",
    "angermuende",
    "schwedt",
    "eberswalde",
    "bernau",
    "fürstenwalde",
    "fuerstenwalde",
    "beeskow",
    "lübben",
    "luebben",
    "luckau",
    "senftenberg",
    "finsterwalde",
    "herzberg",
    "nauen",
    "rathenow",
    "luckenwalde",
    "zossen",
    "ludwigsfelde",
    "bad freienwalde",
    "seelow",
    "strausberg",
    "oranienburg",
    "falkensee",
    "werder",
    "templin",
    "prenzlau",
    "bautzen",
    "kamenz",
    "radeberg",
    "freital",
    "pirna",
    "riesa",
    "meissen",
    "meißen",
    "delitzsch",
    "torgau",
    "eilenburg",
    "borna",
    "plauen",
    "annaberg-buchholz",
    "marienberg",
    "aue",
    "schneeberg",
    "crimmitschau",
    "limbach-oberfrohna",
    "weimar",
    "apolda",
    "arnstadt",
    "ilmenau",
    "saalfeld",
    "sonneberg",
    "greiz",
    "pößneck",
    "poessneck",
    "schmalkalden",
    "meiningen",
    "suhl",
    "mühlhausen",
    "muehlhausen",
    "nordhausen",
    "eisenach",
    "gotha",
    "altenburg",
    "bad langensalza",
    "leinefelde",
    "zeulenroda",
    "saalfeld-rudolstadt",
    "gera",
    "stadtilm",
    "schleiz",
    "lobenstein",
    "gardelegen",
    "wernigerode",
    "quedlinburg",
    "halberstadt",
    "stendal",
    "salzwedel",
    "tangerhütte",
    "tangerhuette",
    "zerbst",
    "köthen",
    "koethen",
    "bitterfeld",
    "wolfen",
    "merseburg",
    "naumburg",
    "zeitz",
    "grimma",
    "döbeln",
    "doebeln",
    "wurzen",
    "oschatz",
    "finsterwalde",
    "spremberg",
    "forst",
    "guben",
    "eisenhüttenstadt",
    "eisenhuettenstadt",
    "fuerstenberg",
    "neustrelitz",
    "wolgast",
    "anklam",
    "pasewalk",
    "demmin",
    "greifswald",
    "waren",
    "neubrandenburg",
)

SERPER_POSITIVE_TERMS = (
    "kontakt",
    "impressum",
    *GU_ROLE_KEYWORDS,
    *RETAIL_BUILD_KEYWORDS,
    *RETAIL_CHAIN_KEYWORDS,
    *RETAIL_REFERENCE_KEYWORDS,
    "filiale",
    "neubau",
    "umbau",
    "sanierung",
    "revitalisierung",
    "erweiterung",
    "ostdeutschland",
    "brandenburg",
    "sachsen",
    "thüringen",
    "thueringen",
    "leipzig",
    "dresden",
    "chemnitz",
    "erfurt",
    "cottbus",
    "halle",
    "landkreis",
    "kleinstadt",
    "gemeinde",
    "regional",
    "mittelständisch",
    "mittelstaendisch",
    "familienunternehmen",
    "meisterbetrieb",
    "inhabergeführt",
    "inhabergefuehrt",
    *DE_OST_REGION_KEYWORDS,
    *DE_OST_PLACE_MARKERS[:40],
)

SERPER_NEGATIVE_TERMS = (
    "vergabemarktplatz",
    "ausschreibung",
    "stadt leipzig",
    "stadt erfurt",
    "dezernat",
    "landkreis",
    "gemeinde ",
    "ihk ",
    "handelskammer",
    "wirtschaftsförderung",
    "gründerzentrum",
    "technologiezentrum",
    "hochschule",
    "universität",
    "ministerium",
    "senatskanzlei",
    "forum",
    "blog.",
    "11880.com",
    "11880.",
    "wikipedia",
    "olx",
    "allegro",
    "amazon.",
    "ebay.",
    "praca",
    "kariera",
    "oferty pracy",
    "poradnik",
    "tutorial",
    "diy ",
    "agregat",
    "stellenangebot",
    "karriere",
    "öffnungszeiten",
    "oeffnungszeiten",
    "filialfinder",
    "wochenangebot",
    "shopfitting",
    "ladeneinrichtung",
    "ladenausstattung",
    "ladenausbau",
    "einrichtungshaus",
    "store design",
    "innenausbau",
    "innenausstatter",
    "messebau",
    "küchenbau",
    "kuechenbau",
    "möbelbau",
    "moebelbau",
    "architekturbüro",
    "architekturbuero",
    "planungsbüro",
    "planungsbuero",
    "fachplanung",
    "projektsteuerung",
    "projektentwickler",
    "facility management",
    "gebäudereinigung",
    "gebaeudereinigung",
    "immobilienmakler",
    "straßenbau",
    "strassenbau",
    "kanalbau",
    "gartenbau",
    "dachdecker",
    "malerbetrieb",
    "elektroinstallateur",
    "strabag",
    "hochtief",
    "bilfinger",
    "porr.de",
    "porr ",
    "goldbeck",
    "implenia",
    "zech group",
    "max bögl",
    "max boegl",
    "züblin",
    "zueblin",
    "leonhard weiss",
    "habau",
    "vinci",
    "bouygues",
    "konzern",
    "weltweit",
    "internationaler konzern",
)

LARGE_COMPANY_DOMAINS_EXTRA = frozenset(
    {
        "max-boegl.de",
        "ed-zueblin.de",
        "leonhard-weiss.de",
        "habau.com",
        "vinci.com",
        "porr.de",
    }
)

LARGE_COMPANY_NAME_MARKERS_EXTRA = (
    "max bögl",
    "max boegl",
    "ed. züblin",
    "züblin",
    "leonhard weiss",
    "habau",
)

SMALL_COMPANY_PAGE_MARKERS_EXTRA = (
    "ortsansässig",
    "ortsansaessig",
    "inhabergeführtes bauunternehmen",
    "inhabergefuehrtes bauunternehmen",
    "traditionsreiches bauunternehmen",
    "inhabergeführtes unternehmen",
    "inhabergefuehrtes unternehmen",
    "überregional",
    "ueberregional",
)

SMALL_COMPANY_DISCOVERY_TERMS_EXTRA = (
    "mittelständisch",
    "mittelstaendisch",
    "inhabergefuehrt",
    "familienbetrieb",
    "ortsansässig",
    "ortsansaessig",
    "traditionsreich",
    "hochbau",
    "schlüsselfertig",
    "schluesselfertig",
    "komplettbau",
    "filialneubau",
    "handelsbau",
)
